---
  - hosts: all
    sudo: yes
    gather_facts: no
    remote_user: vagrant
    tasks:
      - name: Install ssh key
        authorized_key:
          user: vagrant
          key: "{{ lookup('file', '/Users/paulrichter/.ssh/ansible_paul.pub') }}"
          state: present
