---
-  hosts: webservers
   tasks:
     - name: Say hi
       shell: echo Hello from the other side
       register: reply
     - name: Show me what the server said
       debug:
         msg: "{{ reply }}"
     - name: Install git with yum
       yum:
         name: git
         state: latest
       become: yes # equivalent to 'sudo'
